### ISSUE TITLE
Regex issue with html

### ISSUE THREAD

**Issue by VadimDez** [jcrowe206/BadWordFilter#2]
Found an issue when tried to filter string that contains html, regex matches part of html tag.
My case was:

``` php
...
var_dump($filter->clean('<h3>bad word</h3>some text'));
// output: <h3>*******d</h3>some text
// expected: <h3>b******d</h3>some text
```

**Comment by jcrowe206** [comment]
Sorry for the late reply! This has been fixed in the most recent version (v2.1.2). Thanks for bringing it to my attention.
